### ISSUE TITLE
Unable to fine index.coffee in project root

### ISSUE THREAD

**Issue by Sawtaytoes** [sailrish/heroku-buildpack-coffee#2]
Seems it's searching in src/ for *.coffee, but that's not where I've put mine; it's in the project root as index.coffee. Is there some way to accommodate for this use case?

**Comment by sailrish** [comment]
Hmm.  I agree that hardcoding to `src/*.coffee` is a bit restrictive.  But I don't know of a way where the buildpack can take in options so that you can specify a custom project root.  And you can't put *.coffee files right at the root directory because coffee files have to be in a separate directory from the generated .js files.  Perhaps you could use a build system like grunt to copy all your coffee files to src/ before they are compiled down to .js in the target/ folder? I'm sorry, I'm not an expert at buildpacks, or at creating fancy build systems for node.js projects.

**Comment by Sawtaytoes** [comment]
I forked it (https://github.com/Saturn2888/heroku-buildpack-coffee) and tried to make it point at index.coffee in the project root hard-coded and then still compile to index.js in the current directory.

Got it working for me! Going to update the Readme.
